[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.0
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D VERSION='"dev"'
