name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 3 * * 0'  # every Sunday at 03:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Delete workflow runs older than 30 days
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 10
          keep_minimum_runs: 2
